name: 'Go Test, Build, and Coverage'
description: 'Runs tests, builds, and generates coverage reports for Go projects'

inputs:
  go-version:
    description: 'The Go version to use'
    required: false
    default: '1.23'
  gh-go-modules-user:
    description: 'GitHub user for private Go modules'
    required: true
  gh-go-modules-pat:
    description: 'GitHub PAT for private Go modules'
    required: true

runs:
  using: "composite"
  steps:
    - name: GO Test & Build
      uses: japhy-team/gh-actions/go-test-n-build@main
      with:
        go-version: ${{ inputs.go-version }}
        gh-go-modules-user: ${{ inputs.gh-go-modules-user }}
        gh-go-modules-pat: ${{ inputs.gh-go-modules-pat }}

    - name: GO Badge
      uses: japhy-team/gh-actions/go-badge@main
      with:
        gh-go-modules-user: ${{ inputs.gh-go-modules-user }}
        gh-go-modules-pat: ${{ inputs.gh-go-modules-pat }}

    - name: Go Coverage Report
      uses: japhy-team/gh-actions/go-coverage-report@rdu-24-10-deadcode-fix-action
      with:
        gh-go-modules-user: ${{ inputs.gh-go-modules-user }}
        gh-go-modules-pat: ${{ inputs.gh-go-modules-pat }}

    - name: GO Deadcode
      uses: japhy-team/gh-actions/go-deadcode@main
      with:
        gh-go-modules-user: ${{ inputs.gh-go-modules-user }}
        gh-go-modules-pat: ${{ inputs.gh-go-modules-pat }}
