name: 'Go Module Branch Validator'
description: 'Ensures all github.com/japhy-team/* dependencies use commits from the main branch'

inputs:
  go-version:
    description: 'The Go version to use'
    required: false
    default: '1.23'
  gh-go-modules-user:
    description: 'GitHub user for private Go modules'
    required: true
  gh-go-modules-pat:
    description: 'GitHub PAT for private Go modules'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: stable
        cache: false

    - name: Cache Go modules and build
      uses: actions/cache@v4
      with:
        path: |
          /home/runner/.cache/go-build
          /home/runner/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Debug cache manifest
      shell: bash
      run: |
        echo "=== Checking for manifest.txt ==="
        if [ -f manifest.txt ]; then
          echo "Content of manifest.txt:"
          cat manifest.txt
        else
          echo "manifest.txt not found in current directory"
        fi
        echo "=== Checking cache paths ==="
        ls -la /home/runner/.cache/go-build 2>/dev/null || echo "go-build cache not found"
        ls -la /home/runner/go/pkg/mod 2>/dev/null || echo "go mod cache not found"

    - name: Set up Go modules authentication
      shell: bash
      run: |
        go get github.com/japhy-team/ruben
        go install github.com/japhy-team/ruben && ruben
        ruben module-main-check
        go mod tidy
