name: 'Go Test, Build, and Coverage'
description: 'Runs tests, builds, and generates coverage reports for Go projects'

inputs:
  go-version:
    description: 'The Go version to use'
    required: false
    default: '1.23'
  gh-go-modules-user:
    description: 'GitHub user for private Go modules'
    required: true
  gh-go-modules-pat:
    description: 'GitHub PAT for private Go modules'
    required: true

runs:
  using: "composite"
  steps:
  - name: Checkout
    uses: actions/checkout@v4

  - name: Set up Go
    uses: actions/setup-go@v4
    with:
      go-version: ${{ inputs.go-version }}
      cache: false

  - name: Cache Go modules and build
    uses: actions/cache@v4
    with:
      path: |
        /home/runner/.cache/go-build
        /home/runner/go/pkg/mod
      key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      restore-keys: |
        ${{ runner.os }}-go-

  - name: code-coverage
    uses: fgrosse/go-coverage-report@v1.2.0
    with:
      coverage-artifact-name: "code-coverage"
      coverage-file-name: "coverage.out"
