name: 'Go Test, Build, and Coverage'
description: 'Runs tests, builds, and generates coverage reports for Go projects'

runs:
  using: "composite"
  steps:
    - name: "Code coverage report"
      if: github.event_name == 'pull_request'
      runs-on: self-hosted
      needs: test
      steps:
        - uses: fgrosse/go-coverage-report@v1.0.2
          with:
            coverage-artifact-name: "code-coverage"
            coverage-file-name: "coverage.out"
